### ISSUE TITLE
WS2017 Project Completion

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#682]
Here are a few todos, that are still open for the Android Praktikum Guys

- [x] #272 Creating a fancy video
- [ ] #674 Daoize Cache Manager
- [x] #659 Not all rooms shown till refreshed - kordian
- [x] #653 Exception when sending text in chat - kordian
- [ ] #587 Comment Bot - paulius
- [x] #586 SonarQube?
- [x] #574 Calender does not display past events - oli
- [x] #568 Code Coverage - paulius
- [x] #567 Add CheckStyle - paulius
- [ ] #356 Code Quality
- [x] #640 NewsDaoTest.cleanUpOldTest sometimes failing
- [x] Send me a copy of the presentation
- [x] Send me the visio files for all graphs you made
- [x] Send me all the source files for the fancy video
- [ ] Finish documentation - this needs to be complete and has a big grade impact.

I have to submit the Grading till the Wednesday, 07.03.2018 at the very latest. Please have everything done by then, otherwise this might impact the final outcome. Each of you gets a separate grade, but also team effort counts. So anyone feeling he has not yet lived up to their standards, now is your time to shine :star2:

**Comment by kordianbruck** [comment]
Alrighty, we're done with the restructure. Let us know, what you guys think. :heart:

**Comment by psukys** [comment]
Related documentation:

 - [Quality Assurance](https://github.com/TCA-Team/TumCampusApp/wiki/Quality-Assurance)
 - [Code style with Checkstyle](https://github.com/TCA-Team/TumCampusApp/wiki/Code-style-with-Checkstyle)
 - [Writing tests with Robolectric](https://github.com/TCA-Team/TumCampusApp/wiki/Writing-tests-with-Robolectric) (Working on it)
